part of 'app_localizations.dart';

const Map<String, List<String>> _weekdays = <String, List<String>>{
  'ja': <String>['月', '火', '水', '木', '金', '土', '日'],
  'en': <String>['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  'zh': <String>['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
};

const Map<String, Map<String, String>>
_localizedText = <String, Map<String, String>>{
  'ja': <String, String>{
    'appName': 'ガラ写',
    'statusCarrierMark': '写',
    'confirmKeyLabel': 'OK',
    'stickerSelectionPrefix': '貼',
    'homeTakePhoto': '写真を撮る',
    'homeTakeVideo': '動画を撮る',
    'homeEditPhoto': '写真を編集する',
    'keyHome': 'ホーム',
    'keyBack': '戻る',
    'keySticker': 'スタンプ',
    'keyDecorate': 'デコる',
    'keySave': '保存',
    'keyShare': 'シェア',
    'keySaveShare': '保存/シェア',
    'keyDisabled': '---',
    'modeReady': '待機',
    'modeMove': '移動',
    'modeScale': '拡縮',
    'busyLoading': '読み込み中...',
    'busyProcessing': '処理中...',
    'busyOpeningCamera': 'カメラを起動しています...',
    'busyOpeningVideoCamera': '動画カメラを起動しています...',
    'busyReadingCapturedPhoto': '撮影した写真を読み込んでいます...',
    'busyOpeningAlbum': 'アルバムを開いています...',
    'busyProcessingPhoto': '写真を加工しています...',
    'busyProcessingAlbumPhoto': 'アルバムの写真を加工しています...',
    'busyPreparingFaceRetouch': '顔加工を更新しています...',
    'busyPreparingSaveImage': '保存用の画像を作っています...',
    'busyPreparingShareImage': '共有用の画像を作っています...',
    'busyAutoSavingVideo': '動画を加工して自動保存しています...',
    'busySavingVideo': '動画を保存しています...',
    'busyOpeningShareSheet': '共有シートを開いています...',
    'busyDeletingVideo': '動画を削除しています...',
    'panelTitleAddSticker': 'スタンプ追加',
    'panelTitleFaceRetouch': '顔加工',
    'panelTitleVideoMenu': '動画メニュー',
    'panelTitleEditMenu': '編集メニュー',
    'menuHintTapSelect': 'タップで選択・決定',
    'livePhotoAction': '撮影',
    'liveVideoAction': '録画',
    'liveStopAction': '停止',
    'liveRetryVideoAction': '再録画',
    'liveSelectionShot': '撮影',
    'liveSelectionStandby': '待機',
    'liveSelectionError': 'ERR',
    'liveSelectionRecording': '録画',
    'liveSelectionClip': '保存',
    'liveStatusPhoto': '写真',
    'liveStatusVideo': '動画',
    'liveStatusClipReady': '保存OK',
    'liveHintTakePhoto': 'OKで撮影',
    'liveHintRecordVideo': 'OKで録画',
    'liveHintStopRecording': 'OKで停止',
    'liveHintSaveOrShare': '保存/シェアできます',
    'liveShellModeCamera': '写',
    'liveShellModeVideo': '動',
    'cameraInitializingLabel': 'カメラを起動中...',
    'recordingStartedMessage': '録画を開始しました。',
    'shareSheetOpenedMessage': '共有シートを開きました。',
    'recordedVideoDeletedMessage': '録画した動画を削除しました。',
    'genericVideoActionFailedMessage': '動画の操作に失敗しました。',
    'genericVideoProcessFailedMessage': '動画の処理に失敗しました。',
    'imageLoadedMessage': '画像を読み込みました。',
    'imageLoadFailedMessage': '画像の読み込みに失敗しました。',
    'selectPhotoFirstMessage': '先に写真を選択してください。',
    'stickerAddedMessage': 'スタンプを追加しました。',
    'selectStickerToDeleteMessage': '削除するスタンプを選択してください。',
    'stickerDeletedMessage': 'スタンプを削除しました。',
    'addStickerFirstMessage': '先にスタンプを追加してください。',
    'stickerSelectedMessage': 'スタンプを選択しました。',
    'moveModeMessage': '移動モード',
    'scaleModeMessage': '拡大縮小モード',
    'faceRetouchFailedMessage': '顔加工の更新に失敗しました。',
    'faceRetouchNoFaceMessage': '顔が見つからなかったため顔加工できません。',
    'saveFailedMessage': '保存に失敗しました。',
    'shareFailedMessage': '共有に失敗しました。',
    'sharePhotoText': 'ガラ写で加工しました',
    'shareVideoText': 'ガラ写で撮った動画です',
    'savePermissionDeniedMessage': '写真アプリに保存する権限がありません。設定をご確認ください。',
    'savePhotoFailedMessage': '写真アプリへの保存に失敗しました。',
    'saveVideoMissingMessage': '保存する動画が見つかりません。',
    'saveVideoFailedMessage': '動画の保存に失敗しました。',
    'shareVideoMissingMessage': '共有する動画が見つかりません。',
    'imagePickCanceledMessage': '画像の選択をキャンセルしました。',
    'videoResultMissingMessage': '動画の加工結果を受け取れませんでした。',
    'videoRenderFailedMessage': '動画を仕上げられませんでした。',
    'photoModeOnlyMessage': '写真モードではありません。',
    'videoModeOnlyMessage': '動画モードではありません。',
    'takePhotoFailedMessage': '撮影に失敗しました。もう一度お試しください。',
    'startRecordingFailedMessage': '録画を開始できませんでした。',
    'recordingNotStartedMessage': '録画はまだ始まっていません。',
    'finishVideoStyleFailedMessage': '動画を仕上げられませんでした。',
    'noCameraFoundMessage': 'カメラが見つかりません。',
    'openVideoCameraFailedMessage': '動画カメラを起動できませんでした。権限と端末設定を確認してください。',
    'openCameraFailedMessage': 'カメラを起動できませんでした。権限と端末設定を確認してください。',
    'cameraNotReadyMessage': 'カメラの準備ができていません。',
    'recordVideoFirstMessage': '先に動画を録画してください。',
    'cannotSwitchWhileRecordingMessage': '録画中はカメラを切り替えられません。',
    'cannotSwitchWithUnsavedClipMessage': '保存前の動画があるためカメラを切り替えられません。',
    'frontCameraUnavailableMessage': '内カメラが使えない端末です。',
    'backCameraUnavailableMessage': '外カメラが使えない端末です。',
    'lensFront': '内カメラ',
    'lensBack': '外カメラ',
    'lensToggleFront': '内カメ ⇄',
    'lensToggleBack': '外カメ ⇄',
    'stickerHeartRed': 'ハート (赤)',
    'stickerHeartPink': 'ハート (ピンク)',
    'stickerStarYellow': 'スター (黄)',
    'stickerStarOrange': 'スター (オレンジ)',
    'stickerSparkleGold': 'キラキラ (ゴールド)',
    'stickerSparklePink': 'キラキラ (ピンク)',
    'menuSave': '保存する',
    'menuShare': 'シェアする',
    'menuDelete': '削除',
    'faceRetouchOff': 'OFF',
    'faceRetouchCute': 'かわいく',
    'faceRetouchMenuLabel': '顔加工',
    'videoAutoSaveRetryFallbackMessage': '自動保存に失敗しました。保存/シェアからやり直せます。',
    'unsupportedImageFormatMessage': '読み込めない画像形式です。',
    'noneShort': 'なし',
  },
  'en': <String, String>{
    'appName': 'garasha',
    'statusCarrierMark': 'G!',
    'confirmKeyLabel': 'OK',
    'stickerSelectionPrefix': 'ST',
    'homeTakePhoto': 'Take photo',
    'homeTakeVideo': 'Record video',
    'homeEditPhoto': 'Edit photo',
    'keyHome': 'Home',
    'keyBack': 'Back',
    'keySticker': 'Sticker',
    'keyDecorate': 'Decor',
    'keySave': 'Save',
    'keyShare': 'Share',
    'keySaveShare': 'Save/Share',
    'keyDisabled': '---',
    'modeReady': 'Ready',
    'modeMove': 'Move',
    'modeScale': 'Scale',
    'busyLoading': 'Loading...',
    'busyProcessing': 'Processing...',
    'busyOpeningCamera': 'Opening camera...',
    'busyOpeningVideoCamera': 'Opening video camera...',
    'busyReadingCapturedPhoto': 'Loading the captured photo...',
    'busyOpeningAlbum': 'Opening library...',
    'busyProcessingPhoto': 'Processing photo...',
    'busyProcessingAlbumPhoto': 'Processing library photo...',
    'busyPreparingFaceRetouch': 'Updating face retouch...',
    'busyPreparingSaveImage': 'Preparing photo to save...',
    'busyPreparingShareImage': 'Preparing photo to share...',
    'busyAutoSavingVideo': 'Finishing and auto-saving video...',
    'busySavingVideo': 'Saving video...',
    'busyOpeningShareSheet': 'Opening share sheet...',
    'busyDeletingVideo': 'Deleting video...',
    'panelTitleAddSticker': 'Add sticker',
    'panelTitleFaceRetouch': 'Face retouch',
    'panelTitleVideoMenu': 'Video menu',
    'panelTitleEditMenu': 'Edit menu',
    'menuHintTapSelect': 'Tap to select or confirm',
    'livePhotoAction': 'Shoot',
    'liveVideoAction': 'Record',
    'liveStopAction': 'Stop',
    'liveRetryVideoAction': 'Retake',
    'liveSelectionShot': 'SHOT',
    'liveSelectionStandby': 'STBY',
    'liveSelectionError': 'ERR',
    'liveSelectionRecording': 'REC',
    'liveSelectionClip': 'CLIP',
    'liveStatusPhoto': 'PHOTO',
    'liveStatusVideo': 'VIDEO',
    'liveStatusClipReady': 'CLIP READY',
    'liveHintTakePhoto': 'Press OK to shoot',
    'liveHintRecordVideo': 'Press OK to record',
    'liveHintStopRecording': 'Press OK to stop',
    'liveHintSaveOrShare': 'Save or share this clip',
    'liveShellModeCamera': 'CAM',
    'liveShellModeVideo': 'MOV',
    'cameraInitializingLabel': 'Starting camera...',
    'recordingStartedMessage': 'Recording started.',
    'shareSheetOpenedMessage': 'Share sheet opened.',
    'recordedVideoDeletedMessage': 'Recorded video deleted.',
    'genericVideoActionFailedMessage': 'Could not complete the video action.',
    'genericVideoProcessFailedMessage':
        'Could not finish processing the video.',
    'imageLoadedMessage': 'Photo loaded.',
    'imageLoadFailedMessage': 'Could not load the photo.',
    'selectPhotoFirstMessage': 'Select a photo first.',
    'stickerAddedMessage': 'Sticker added.',
    'selectStickerToDeleteMessage': 'Select a sticker to delete.',
    'stickerDeletedMessage': 'Sticker deleted.',
    'addStickerFirstMessage': 'Add a sticker first.',
    'stickerSelectedMessage': 'Sticker selected.',
    'moveModeMessage': 'Move mode',
    'scaleModeMessage': 'Scale mode',
    'faceRetouchFailedMessage': 'Could not update face retouch.',
    'faceRetouchNoFaceMessage':
        'No face was found, so face retouch is unavailable.',
    'saveFailedMessage': 'Could not save the photo.',
    'shareFailedMessage': 'Could not share the photo.',
    'sharePhotoText': 'Edited with garasha',
    'shareVideoText': 'Shot with garasha',
    'savePermissionDeniedMessage':
        'Photo library save permission is missing. Check Settings.',
    'savePhotoFailedMessage': 'Could not save to the Photos app.',
    'saveVideoMissingMessage': 'The video to save could not be found.',
    'saveVideoFailedMessage': 'Could not save the video.',
    'shareVideoMissingMessage': 'The video to share could not be found.',
    'imagePickCanceledMessage': 'Image selection was canceled.',
    'videoResultMissingMessage': 'The processed video result was empty.',
    'videoRenderFailedMessage': 'Could not finish the video style.',
    'photoModeOnlyMessage': 'This action is only available in photo mode.',
    'videoModeOnlyMessage': 'This action is only available in video mode.',
    'takePhotoFailedMessage': 'Could not take the photo. Try again.',
    'startRecordingFailedMessage': 'Could not start recording.',
    'recordingNotStartedMessage': 'Recording has not started yet.',
    'finishVideoStyleFailedMessage': 'Could not finish the styled video.',
    'noCameraFoundMessage': 'No camera was found.',
    'openVideoCameraFailedMessage':
        'Could not open the video camera. Check permissions and device settings.',
    'openCameraFailedMessage':
        'Could not open the camera. Check permissions and device settings.',
    'cameraNotReadyMessage': 'The camera is not ready yet.',
    'recordVideoFirstMessage': 'Record a video first.',
    'cannotSwitchWhileRecordingMessage':
        'You cannot switch cameras while recording.',
    'cannotSwitchWithUnsavedClipMessage':
        'You cannot switch cameras while an unsaved clip remains.',
    'frontCameraUnavailableMessage':
        'This device does not have a front camera.',
    'backCameraUnavailableMessage': 'This device does not have a rear camera.',
    'lensFront': 'front camera',
    'lensBack': 'rear camera',
    'lensToggleFront': 'Front ⇄',
    'lensToggleBack': 'Rear ⇄',
    'stickerHeartRed': 'Heart (red)',
    'stickerHeartPink': 'Heart (pink)',
    'stickerStarYellow': 'Star (yellow)',
    'stickerStarOrange': 'Star (orange)',
    'stickerSparkleGold': 'Sparkle (gold)',
    'stickerSparklePink': 'Sparkle (pink)',
    'menuSave': 'Save',
    'menuShare': 'Share',
    'menuDelete': 'Delete',
    'faceRetouchOff': 'Off',
    'faceRetouchCute': 'Cute',
    'faceRetouchMenuLabel': 'Face retouch',
    'videoAutoSaveRetryFallbackMessage':
        'Auto-save failed. You can retry from Save/Share.',
    'unsupportedImageFormatMessage': 'This image format is not supported.',
    'noneShort': 'None',
  },
  'zh': <String, String>{
    'appName': 'garasha',
    'statusCarrierMark': 'G!',
    'confirmKeyLabel': 'OK',
    'stickerSelectionPrefix': '贴',
    'homeTakePhoto': '拍照片',
    'homeTakeVideo': '录视频',
    'homeEditPhoto': '编辑照片',
    'keyHome': '主页',
    'keyBack': '返回',
    'keySticker': '贴纸',
    'keyDecorate': '装饰',
    'keySave': '保存',
    'keyShare': '分享',
    'keySaveShare': '保存/分享',
    'keyDisabled': '---',
    'modeReady': '待机',
    'modeMove': '移动',
    'modeScale': '缩放',
    'busyLoading': '加载中...',
    'busyProcessing': '处理中...',
    'busyOpeningCamera': '正在打开相机...',
    'busyOpeningVideoCamera': '正在打开视频相机...',
    'busyReadingCapturedPhoto': '正在读取拍摄的照片...',
    'busyOpeningAlbum': '正在打开相册...',
    'busyProcessingPhoto': '正在处理照片...',
    'busyProcessingAlbumPhoto': '正在处理相册里的照片...',
    'busyPreparingFaceRetouch': '正在更新脸部修饰...',
    'busyPreparingSaveImage': '正在准备保存照片...',
    'busyPreparingShareImage': '正在准备分享照片...',
    'busyAutoSavingVideo': '正在处理并自动保存视频...',
    'busySavingVideo': '正在保存视频...',
    'busyOpeningShareSheet': '正在打开分享面板...',
    'busyDeletingVideo': '正在删除视频...',
    'panelTitleAddSticker': '添加贴纸',
    'panelTitleFaceRetouch': '脸部修饰',
    'panelTitleVideoMenu': '视频菜单',
    'panelTitleEditMenu': '编辑菜单',
    'menuHintTapSelect': '点击选择或确认',
    'livePhotoAction': '拍摄',
    'liveVideoAction': '录制',
    'liveStopAction': '停止',
    'liveRetryVideoAction': '重录',
    'liveSelectionShot': '拍摄',
    'liveSelectionStandby': '待机',
    'liveSelectionError': '错误',
    'liveSelectionRecording': '录制',
    'liveSelectionClip': '片段',
    'liveStatusPhoto': '照片',
    'liveStatusVideo': '视频',
    'liveStatusClipReady': '片段就绪',
    'liveHintTakePhoto': '按 OK 拍摄',
    'liveHintRecordVideo': '按 OK 录制',
    'liveHintStopRecording': '按 OK 停止',
    'liveHintSaveOrShare': '可保存或分享',
    'liveShellModeCamera': '拍',
    'liveShellModeVideo': '录',
    'cameraInitializingLabel': '正在启动相机...',
    'recordingStartedMessage': '已开始录制。',
    'shareSheetOpenedMessage': '已打开分享面板。',
    'recordedVideoDeletedMessage': '已删除录制的视频。',
    'genericVideoActionFailedMessage': '视频操作失败。',
    'genericVideoProcessFailedMessage': '视频处理失败。',
    'imageLoadedMessage': '照片已载入。',
    'imageLoadFailedMessage': '照片载入失败。',
    'selectPhotoFirstMessage': '请先选择照片。',
    'stickerAddedMessage': '已添加贴纸。',
    'selectStickerToDeleteMessage': '请选择要删除的贴纸。',
    'stickerDeletedMessage': '已删除贴纸。',
    'addStickerFirstMessage': '请先添加贴纸。',
    'stickerSelectedMessage': '已选中贴纸。',
    'moveModeMessage': '移动模式',
    'scaleModeMessage': '缩放模式',
    'faceRetouchFailedMessage': '脸部修饰更新失败。',
    'faceRetouchNoFaceMessage': '没有检测到人脸，无法进行脸部修饰。',
    'saveFailedMessage': '保存失败。',
    'shareFailedMessage': '分享失败。',
    'sharePhotoText': '使用 garasha 编辑',
    'shareVideoText': '使用 garasha 拍摄',
    'savePermissionDeniedMessage': '没有保存到照片 App 的权限。请检查设置。',
    'savePhotoFailedMessage': '保存到照片 App 失败。',
    'saveVideoMissingMessage': '找不到要保存的视频。',
    'saveVideoFailedMessage': '视频保存失败。',
    'shareVideoMissingMessage': '找不到要分享的视频。',
    'imagePickCanceledMessage': '已取消选择图片。',
    'videoResultMissingMessage': '没有收到处理后的视频结果。',
    'videoRenderFailedMessage': '无法完成视频效果处理。',
    'photoModeOnlyMessage': '该操作仅支持照片模式。',
    'videoModeOnlyMessage': '该操作仅支持视频模式。',
    'takePhotoFailedMessage': '拍摄失败，请重试。',
    'startRecordingFailedMessage': '无法开始录制。',
    'recordingNotStartedMessage': '录制尚未开始。',
    'finishVideoStyleFailedMessage': '无法完成视频风格处理。',
    'noCameraFoundMessage': '没有找到相机。',
    'openVideoCameraFailedMessage': '无法打开视频相机。请检查权限和设备设置。',
    'openCameraFailedMessage': '无法打开相机。请检查权限和设备设置。',
    'cameraNotReadyMessage': '相机尚未准备好。',
    'recordVideoFirstMessage': '请先录制视频。',
    'cannotSwitchWhileRecordingMessage': '录制时无法切换相机。',
    'cannotSwitchWithUnsavedClipMessage': '还有未保存的视频片段，暂时无法切换相机。',
    'frontCameraUnavailableMessage': '当前设备不支持前置相机。',
    'backCameraUnavailableMessage': '当前设备不支持后置相机。',
    'lensFront': '前置相机',
    'lensBack': '后置相机',
    'lensToggleFront': '前置 ⇄',
    'lensToggleBack': '后置 ⇄',
    'stickerHeartRed': '爱心（红）',
    'stickerHeartPink': '爱心（粉）',
    'stickerStarYellow': '星星（黄）',
    'stickerStarOrange': '星星（橙）',
    'stickerSparkleGold': '闪光（金）',
    'stickerSparklePink': '闪光（粉）',
    'menuSave': '保存',
    'menuShare': '分享',
    'menuDelete': '删除',
    'faceRetouchOff': '关闭',
    'faceRetouchCute': '可爱',
    'faceRetouchMenuLabel': '脸部修饰',
    'videoAutoSaveRetryFallbackMessage': '自动保存失败。你可以在保存/分享里重试。',
    'unsupportedImageFormatMessage': '不支持该图片格式。',
    'noneShort': '无',
  },
};
